### ISSUE TITLE
implement 503 page

### ISSUE THREAD

**Issue by sahityagaurav4210** [sahityagaurav4210/book-junction-admin#36]
add 503 page to the project. this page should be shown to the user(s) when

1. the backend is down for maintenance.
2. the api is not returning the response.

**Comment by sahityagaurav4210** [comment]
take refrence from https://github.com/sahityagaurav4210/book-junction-admin/issues/34 and https://github.com/sahityagaurav4210/book-junction-admin/issues/41

**Comment by sahityagaurav4210** [comment]
![503](https://github.com/sahityagaurav4210/book-junction-admin/assets/59797906/81c57aec-acc7-4c08-bc27-d79bf70852b3)
### use this image while rendering page.pug file

**Comment by SheenuSembhi** [comment]
I have started working on this ticket

**Comment by sahityagaurav4210** [comment]
ticket hui @SheenuSembhi

**Comment by SheenuSembhi** [comment]
Hii @sahityagaurav4210  The ticket is almost done , will raise PR in sometime

**Comment by sahityagaurav4210** [comment]
@SheenuSembhi  pls share the image which you've shared on whatsapp

**Comment by SheenuSembhi** [comment]
![Screenshot from 2024-05-04 22-10-10](https://github.com/sahityagaurav4210/book-junction-admin/assets/167019340/7c2d2bf6-da73-4912-83bc-311cf9d24447)

@sahityagaurav4210  find the image attached , I will replace this image when you'll provide me

**Comment by sahityagaurav4210** [comment]
@SheenuSembhi  pls find the image is attached.
![503](https://github.com/sahityagaurav4210/book-junction-admin/assets/59797906/ab9703b4-20c0-402a-a272-f8a17ed5f83d)

**Comment by sahityagaurav4210** [comment]
@SheenuSembhi pls change the url make it offline instead of 503.
also share the code for route which you've written to render the ui.

**Comment by SheenuSembhi** [comment]
![image](https://github.com/sahityagaurav4210/book-junction-admin/assets/167019340/983fa9f3-05e2-4279-ae91-64d050bece50)
 sharing code in a second

**Comment by sahityagaurav4210** [comment]
@SheenuSembhi Oh ho 😓, keep the o of offline small.

**Comment by sahityagaurav4210** [comment]
also share the ss of footer as well

**Comment by SheenuSembhi** [comment]
![image](https://github.com/sahityagaurav4210/book-junction-admin/assets/167019340/d19f57ac-257f-4b83-bdc0-2053a2c2bad2)
I am checking as Its automatically capitilizing the O of offline

**Comment by sahityagaurav4210** [comment]
share the code of route

**Comment by SheenuSembhi** [comment]
![image](https://github.com/sahityagaurav4210/book-junction-admin/assets/167019340/ae1efca0-ef60-4e67-b2e2-17ccf9bbadf4)
![image](https://github.com/sahityagaurav4210/book-junction-admin/assets/167019340/7fd95b2d-dd4e-4735-b2d2-f601b71ef7c8)

**Comment by sahityagaurav4210** [comment]
ok try with http://localhost:3000/offline

**Comment by sahityagaurav4210** [comment]
also change the function name to offline

**Comment by sahityagaurav4210** [comment]
in controllers

**Comment by SheenuSembhi** [comment]
Thanks the url worked, Can you help me with , where to write logic for backend down or api is not returning the response

**Comment by sahityagaurav4210** [comment]
@SheenuSembhi for backend is down, leave the logic for that for now. and for offline check for offline and online events in javascript on web, you'll find it there and show the page on offline event

**Comment by SheenuSembhi** [comment]
please check is it correct
![image](https://github.com/sahityagaurav4210/book-junction-admin/assets/167019340/460ef431-befc-422f-833e-c2634f95d649)

**Comment by sahityagaurav4210** [comment]
add the online event too and test it properly

**Comment by SheenuSembhi** [comment]
![image](https://github.com/sahityagaurav4210/book-junction-admin/assets/167019340/d9369230-402a-4937-a82e-762d36eac6b2)
